/**
 * @author Vasile Fana <vasile.fana@cloudshiftgroup.com>
 * @date 2020-12-02
 * @group CloudShiftGroup
 * @description  This class is responsible for assigning the order to campaign
 *               matching Ids which are used to match the orders to the correct
 *               influencing campaigns.
 *
 * Date          author             Change Description
 * -----------------------------------------------------------------------------------
 * 2020-12-02    Vasile Fana       Created Class
 * 2021-04-21    Andrei Budescu    Deleted Class
 */
public without sharing class OrderToCampaignMatchingIdAssigner {
    
    
}