/**
 * @author Vasile Fana <vasile.fana@cloudshiftgroup.com>
 * @date 2020-12-03
 * @group CloudShiftGroup
 * @description  This class is responsible for finding order's linked campaigns 
 *               and unmatch from these by removing the related campaign memebrs
 *               and influenced room booking records. 
 *
 * Date          author             Change Description
 * -----------------------------------------------------------------------------------
 * 2020-12-03    Vasile Fana       Created Class
 * 2021-04-21    Andrei Budescu    Deleted Class
 */
public without sharing class OrderToCampaignUnmatchingController {

    

}